### ISSUE TITLE
1.20-2.2.0 missing in repo and .jar has wrong api-version

### ISSUE THREAD

**Issue by FynniX** [lukalt/PacketWrapper#2]
Hi,
using maven I cant get the 1.20-2.2.0 version.
Also the PacketWrapper.jar doesnt load up in papermc because api-version 1.20 doesnt exists.

**Comment by lukalt** [comment]
Hi,
thank you for informing me about this. Both issues should be resolved now. Please use release 2.2.1 now: https://github.com/lukalt/PacketWrapper/releases/tag/2.2.1-1.20.

Please let me know if this fixes your issues.

**Comment by FynniX** [comment]
README shows wrong version for the maven dependency.

This would be the correct version: 1.20-2.2.1-SNAPSHOT.

**Comment by lukalt** [comment]
Sorry for the late response. The readme has been updated accordingly in the meanwhile
